# Generated by Django 4.1.3 on 2022-12-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Subscribers',
                'db_table': 'subscribers',
            },
        ),
    ]
